name: JackieWilliamsPhotography
favicon: null
layout_spectrum: 0.335826235357672
typography_spectrum: 0.5924561314750463
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7dae2'
    - '#a1a1aa'
    - '#342f2c'
    - '#706d73'
    - '#170d05'
  brandStrength: 1
  lightness: 0.02020900254137814
  saturation: 0.4380836959462613
  rhythmicContrast: 0.0384521191008389
purpose: []
